spring:
  data:
    mongodb:
      username: rootuser
      password: rootpass
      authentication-database: admin
      host: localhost
      database: product-service
      port: 27017

  application:
    name: product-service

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

server:
  port: 0

