spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service
      username: rootuser
      password: rootpass
      authentication-database: admin
  application:
    name: product-service
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 0

